### ISSUE TITLE
Ajustar efectos

### ISSUE THREAD

**Issue by LeanmFranco** [Cami09111/Mercado-Liebre#1]
Se ve todo muy bien, pero algunos efectos solo se ven en resolución de mas de 1400px, y el carrito debe girar en sentido contrario.

**Comment by Cami09111** [comment]
Ya lo actualicé, no sé si se te vea ya o de pronto mañana, me podrías especificar por favor cuales son los efectos que no se ven? es que lo tengo en 1024-1440 ya que mi compu es 1440
